InformesLegais/blueprints/controles_bp/__init__.py
from flask import Blueprint , jsonify , render_template





conroles_bp = Blueprint('controles', __name__ , url_prefix='/controles')


@conroles_bp.route("/")
def home_controles():
    return render_template("Controles/main.html")


from .ConsolidarPosicaoView import *
from .DadosInvestidores import *
from .SolicitarPosicoes import SolicitarPosicoes

InformesLegais/cadastros_bp/__init__.py
from flask import Blueprint , request , jsonify , render_template , redirect , url_for , send_file
from JCOTSERVICE import ListFundosService , RelPosicaoFundoCotistaService
from bson.objectid import ObjectId
from ..db import db
import pandas as pd
from GERACAO_5401.Representantes import Representante
from GERACAO_5401.Administradores import Adms
from GERACAO_5401.Validador5401 import XML_5401
from dataclasses import asdict
from io import BytesIO
from xml.etree import ElementTree as ET


cadastros = Blueprint('cadastros', __name__ , url_prefix='/cadastros')

@cadastros.route('/cadastros', methods=['GET'])
def buscarFundosJcot():
    list_fundos = ListFundosService("thiago", "tAman1993**").listFundoRequest().to_dict('records')

    consulta = db.fundos.find({})

    codigos = [item['codigo'] for item in consulta]


    for item in list_fundos:
        if item['codigo'] not in codigos:
            db.fundos.insert_one(item)


    return jsonify({"message": "Fundos cadastrados com sucesso!"})

@cadastros.route("/administradores")
def administradores():

    adms = db.administradores.find({})

    admin = [Adms(nome= item['nome'] , cnpj=item['cnpj'] ,  id = str(item['_id'])).to_dict() for item in adms]

    return render_template("Administradores.html" , admin = admin )

@cadastros.route("/administradores_detalhes", methods=['GET' , 'POST'])
def cadastro_administradores_detalhe():

    id = request.args.get('id')
    admin = db.administradores.find_one({'_id':ObjectId(id)})


    if request.method == 'POST':


        cnpj = request.form.get('cnpj')
        nome = request.form.get('nome')
        cpf_representante = request.form.get('cpf_representante')
        representante = request.form.get('representante')
        tel_representante = request.form.get('tel_representante')

        # Define the update query
        update_data = {
            "cnpj": cnpj,
            "nome": nome.strip(),
            "cpf_representante": cpf_representante,
            "representante": representante,
            "tel_representante": tel_representante
        }

        # Update the document in MongoDB
        result = db.administradores.update_one({"_id": ObjectId(id)}, {"$set": update_data})

    return render_template("Administradores_detalhe.html" , admin = admin )

@cadastros.route("/representantes")
def cadastros_representantes():
    representante = Representante(nome="Thiago", telefone="24035621", administrador="36113876000191")

    db.representantes.insert_one(asdict(representante))

    return jsonify(representante)

@cadastros.route("/listar_fundos", methods=['GET'])
def listarFundos():
    page = int(request.args.get('page', 1))
    size = int(request.args.get('size', 10))
    skip = (page - 1) * size

    fundos  = db.fundos.find({}).skip(skip).limit(size)

    retorno = [{
        "id": str(item['_id']) ,
        "codigo": item['codigo'],
        "administrador": item['administrador']
    }  for item in fundos  ]

    total_items = db.fundos.count_documents({})

    return jsonify({
        "total_items": total_items,
        "page": page,
        "size": size,
        "items": retorno
    })

@cadastros.route("/home")
def list_fundos_template():
    
    fundos = db.fundos.find({})
    
    lista_fundos = [{ "id": str(fundo['_id']) , "codigo": fundo['codigo'] , "razaoSocial": fundo['razaoSocial']} for fundo in fundos]
    
    
    return render_template("listar_fundos.html" , fundos=lista_fundos)

@cadastros.route("/editar_fundo", methods=['GET', 'POST'])
def editarFundo():
    fundo_id = request.args.get('id')

    fundo = db.fundos.find_one({'_id': ObjectId(fundo_id)})

    if request.method == 'POST':



        fundo = db.fundos.update_one(
                                    {'_id': ObjectId(request.form.get('id'))} ,
                                    { "$set": { "tipo": request.form['tipoCota'] }}
                                 )


        
        
        return redirect(url_for("cadastros.list_fundos_template"))

    return render_template("form_register.html", fundo=fundo)

@cadastros.route("/posicaoFundo", methods=['GET', 'POST'])
def posicaoJcot():
    codigo_fundo = request.args.get('codigo')
    service = RelPosicaoFundoCotistaService("thiago", "tAman1993**")
    fundo = {"codigo": codigo_fundo ,"dataPosicao": '2024-06-28'}
    df = service.get_posicoes_json(fundo)

    trava = db.posicoes_jcot.find_one({"fundo": codigo_fundo , "data": fundo['dataPosicao']})

    if not trava:
        db.posicoes_jcot.insert_many(df)

    return {"message": f"Posições do fundo  {codigo_fundo} extraidas com sucesso"}

@cadastros.route("/fundossemtiporelatorio" , methods=['GET'])
def relatorio_fundos_sem_cadastro():
    '''rota para gerar em excel o relatório com os fundos sem o tipo de cota cadastrado'''
    fundos = db.fundos.find({})
    df_fundos = pd.DataFrame.from_dict(fundos)

    output = BytesIO()
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        df_fundos[df_fundos['tipo'].isnull()].to_excel(writer, index=False)

    output.seek(0)

    return send_file(output, as_attachment=True, download_name='fundos_sem_cadastro.xlsx', mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

@cadastros.route("/jobs" , methods=['GET'])
def jobs():
    '''rota gerenciar os jobs'''

    jobs = db.celery_taskmeta.find({})

    lista_jobs = [{"status": job['status'] , "result": str(job['result'])  } for job in jobs]

    return render_template("Jobs.html" , jobs = lista_jobs)


@cadastros.route('/consolidador_investidores', methods=['GET', 'POST'])
def consolidador_investidores():

    if request.method == 'POST':
        # print (request.files)
        xml = XML_5401(request.files['arquivo'] , 'validacao')

        for investidor in xml.get_cotistas().to_dict("records"):

            if not db.investidores5401.find_one({"identificacao": investidor["identificacao"]}):
                db.investidores5401.insert_one(investidor)




    return render_template("consolidador_investidores.html")

InformesLegais/extracoes_bp/__init__.py
from flask import Blueprint , request , jsonify , render_template

from InformesLegais.db import db
from InformesLegais.tasks import extrair_posicao_jcot_unique
import pandas as pd
from GERACAO_5401 import Extracao_Quantidades_O2 , client
from GERACAO_5401.extracao_5401_quantidades_o2 import o2Api
from datetime import datetime
from ..tasks import extrair_posicao_o2 , atualizar_investidores_o2
import os


extracoes = Blueprint('extracoes', __name__ , url_prefix='/extracoes')


@extracoes.route("/extrair_jcot")
def extrair_posicoes_jcot():    
    fundos = db.fundos.find({})

    db.posicoesjcot.delete_many({})

    for fundo in fundos:
        fundo['_id'] = str(fundo['_id'])
        fundo['dataPosicao'] = "2024-07-31"
        fundo['fundo'] = fundo['codigo']
        extrair_posicao_jcot_unique.delay(fundo)

    
    return jsonify({"message": "Fundo enviados para extracao"})

@extracoes.route("/atualizar_ativos_intactus")
def atualizar_ativos_02():
    '''atualizar a base de ativos do o2 '''
    db.ativoso2.delete_many({})
    extrator_intactus = Extracao_Quantidades_O2( client, datetime(2024,6,28) )
    fundos = extrator_intactus.get_lista_fundos()


    db.ativoso2.insert_many(fundos)

    return jsonify({"messsage": "Ativos Atualizados"})

@extracoes.route("/extrair_posicao")
def extrair_posicoes_o2():
    '''extracao de posição'''
    api = o2Api("thiago.conceicao", "DBCE0923-9CE3-4597-9E9A-9EAE7479D897")

    headers = {
        'Authorization': f'Bearer {api.get_token()}',
        'Content-Type': 'application/json'
    }
    #consulta de fundos que possuem código jcot

    db.posicoeso2.delete_many({})

    fundos  = db.ativoso2.find({"cd_jcot": { "$ne": "Sem Código" }})


    # fundos  = db.ativoso2.find({"cd_jcot": { "$in": ['763'] }})

     
    #criando as tasks para baixar as posições do o2
    for item in fundos:
        item['_id'] = str(item['_id'])
        item['data'] = '2024-07-31'
        extrair_posicao_o2.delay(item , headers)
    
    return jsonify({"messsage": "Posiçoes Extraídas"})

@extracoes.route("/get_investidores_o2")
def get_investidores():
    '''extracao de investidores o2'''
    api = o2Api("thiago.conceicao", "DBCE0923-9CE3-4597-9E9A-9EAE7479D897")
    #consulta de fundos que possuem código jcot

    atualizar_investidores_o2.delay()

    return jsonify({"messsage": "Posiçoes Extraídas"})

InformesLegais/geracaoInformes_bp/__init__.py
from flask import Blueprint , request , jsonify , render_template , redirect , url_for , flash
from ..db import db
from ..tasks import gerar_5401_por_adm  , extrair_posicao_jcot_unique , extrair_posicao_o2 , extrair_posicao_jcot , extrair_posicao_o2_geral


geracao_informes_bp = Blueprint('geracao_informes', __name__ , url_prefix='/geracao')



def job_criar_fundos(cnpj , documento_5401 ):
    gerador_fundo_5401 = Fundo5401(cnpj)
    fundo = gerador_fundo_5401.transforma_posicao_posicao_informe()

    if fundo is not None:
 
        documento_5401.adicionar_fundos(fundo)
    else:
        pass



@geracao_informes_bp.route("/gerar_arquivo")
def gerar_arquivo_5401():
    fundos = db.fundos.find({})
    adms = []
    for item in fundos:
        if item['administrador'] not in adms:
            adms.append(item['administrador'])




    return render_template("form_geracao_5401.html" , adms = adms)




@geracao_informes_bp.route("/5401" , methods=['POST'])
def gerar_informe_5401():

    try:

        adm = request.form['administrador']

        # gerar_5401_por_adm.delay('08387157000123')

        print (adm)
        #
        # extrair_posicao_jcot.delay()
        #
        # extrair_posicao_o2_geral.delay()

        gerar_5401_por_adm.delay(adm)


        flash(f"Arquivo enviado para geração" ,  'succes')

    except Exception as e:
        flash(f"Erro ao enviar para geração -> {e}", 'danger')



    return redirect(url_for('geracao_informes.gerar_arquivo_5401'))

InformesLegais/templates/Administradores.html
{% extends "main_template.html" %}



{% block content %}

    <h1>Cadastro de Administradores</h1>


    <table class="table">

    <thead>
        <th>Nome</th>
        <th>CNPJ</th>

    </thead>

        {% for adm in admin %}
        <tr>
            <td>{{ adm['nome'] }}</td>
            <td>{{ adm['cnpj'] }}</td>
            <td><a class="btn btn-primary" href="{{ url_for('cadastros.cadastro_administradores_detalhe') }}?id={{ adm['id'] }}">Editar</a></td>
        </tr>


    {% endfor %}


    </table>





{% endblock %}

InformesLegais/templates/Administradores_detalhe.html
{% extends "main_template.html" %}



{% block content %}

<h1>Edição Administrador</h1>

<form action="#" method="POST" class="p-3">
    <input name="id" hidden value="{{ admin['_id'] }}">

    <div class="form-group mb-3">
        <label for="cnpj">CNPJ</label>
        <input name="cnpj" type="text" id="cnpj" class="form-control" value="{{ admin['cnpj'] }}">
    </div>

    <div class="form-group mb-3">
        <label for="nome">Nome</label>
        <input name="nome" type="text" id="nome" class="form-control" value="{{ admin['nome'] }}">
    </div>

    <div class="form-group mb-3">
        <label for="cpf_representante">CPF Representante</label>
        <input name="cpf_representante" type="text" id="cpf_representante" class="form-control" value="{{ admin['cpf_representante'] }}">
    </div>

    <div class="form-group mb-3">
        <label for="representante">Representante</label>
        <input name="representante" type="text" id="representante" class="form-control" value="{{ admin['representante'] }}">
    </div>

    <div class="form-group mb-3">
        <label for="tel_representante">Telefone Representante</label>
        <input name="tel_representante" type="text" id="tel_representante" class="form-control" value="{{ admin['tel_representante'] }}">
    </div>

    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Concluir Edição">
    </div>
</form>






{% endblock %}

InformesLegais/templates/Jobs.html
{% extends "main_template.html" %}



{% block content %}

<h1>Jobs</h1>

<table class="table">
    
    <thead>
        <th>Status</th>
        <th>Descrição</th>
        <th>Inicio</th>
        <th>Fim</th>
    
    </thead>    


    <tbody>
    {% for job in jobs %}
       <tr>
            <td>{{ job['status'] }}</td>
            <td>{{ job['result'] }}</td>
            <td>{{ job['start_time'] }}</td>
            <td>{{ job['end_time'] }}</td>
        </tr>
    {% endfor %}

    </tbody>



</table>





{% endblock %}

InformesLegais/templates/consolidador_investidores.html
{% extends "main_template.html" %}



{% block content %}
<h1> Consolidador de Investidores</h1>
    <p>Recebe arquivos do 5401 , para consolidar o histórico de investidores do arquivo.</p>

 <form action="#" method="post"  enctype="multipart/form-data">

         <div class="form-group mb-3">
            <label for="nome">Arquivo 5401</label>
            <input name="arquivo" type="file" id="nome" class="form-control">
        </div>
         <div class="form-group mb-3">
            <input type="submit" value="Importar" class=" btn btn-primary form-control">
        </div>
 </form>


{% endblock %}

InformesLegais/templates/form_geracao_5401.html
{% extends "main_template.html" %}



{% block content %}
<h1> Gerar 5401</h1>

 <form action={{ url_for("geracao_informes.gerar_informe_5401") }} method="post">
     {{ form.hidden_tag() }}

    <div class="mb-3">
        {{ form.data.label(class="form-label") }}
        {{ form.data(class="form-select") }}
    </div>

     <div class="mb-3">
        {{ form.administrador.label(class="form-label") }}
        {{ form.administrador(class="form-select") }}
    </div>

       <div class="mb-3">
        {{ form.tipos_5401.label(class="form-label") }}
        {{ form.tipos_5401(class="form-select") }}
    </div>

    <div class="mb-3">
        {{ form.submit(class="btn btn-primary") }}
    </div>
     <a  class="btn btn-primary" href={{ url_for("extracoes.get_investidores") }}>Sincronizar Investidores</a>
 </form>








{% endblock %}

InformesLegais/templates/form_register.html
{% extends "main_template.html" %}



{% block content %}

<h1>Cadastro de Fundos</h1>


<form action="#" method="POST">

    <input name="id"  hidden value="{{ fundo['_id'] }}">

    <label for="fundo">Codigo do Fundo</label>
    <input name="cd_fundo" type="text" id="fundo" value="{{ fundo['codigo']}}">

    <label for="fundo">Fundo</label>
    <select name="tipoCota" type="text" id="fundo">

        {% if fundo['tipo']  == '1' %}
            <option value="">Selecione o Tipo de Cota</option>
             <option selected value="1">UNICA</option>
            <option value="2">SENIOR</option>
            <option value="3">MEZANINO</option>
            <option value="4">SUBORDINADA</option>
            <option value="5">OUTRAS</option>
        {% elif fundo['tipo']  == '2' %}
            <option value="">Selecione o Tipo de Cota</option>
            <option value="1">UNICA</option>
            <option selected value="2">SENIOR</option>
            <option value="3">MEZANINO</option>
            <option value="4">SUBORDINADA</option>
            <option value="5">OUTRAS</option>

        {% elif fundo['tipo']  == '3' %}
            <option value="">Selecione o Tipo de Cota</option>
            <option value="1">UNICA</option>
            <option value="2">SENIOR</option>
            <option selected value="3">MEZANINO</option>
            <option value="4">SUBORDINADA</option>
            <option value="5">OUTRAS</option>

        {% elif fundo['tipo']  == '4' %}
            <option value="">Selecione o Tipo de Cota</option>
            <option value="1">UNICA</option>
            <option value="2">SENIOR</option>
            <option value="3">MEZANINO</option>
            <option selected value="4">SUBORDINADA</option>
            <option value="5">OUTRAS</option>

        {% elif fundo['tipo']  == '5' %}
            <option value="">Selecione o Tipo de Cota</option>
            <option value="1">UNICA</option>
            <option value="2">SENIOR</option>
            <option value="3">MEZANINO</option>
            <option value="4">SUBORDINADA</option>
            <option selected value="5">OUTRAS</option>

        {% else  %}
            <option value="">Selecione o Tipo de Cota</option>
            <option value="1">UNICA</option>
            <option value="2">SENIOR</option>
            <option value="3">MEZANINO</option>
            <option value="4">SUBORDINADA</option>
            <option value="5">OUTRAS</option>

        {% endif %}


    </select>


    <input type="submit" value="Concluir Edição"/>


</form>






{% endblock %}

InformesLegais/templates/listar_fundos.html
{% extends "main_template.html" %}



{% block content %}

<h1>Lista de Fundos Jcot</h1>

<a class="btn btn-primary"  href="{{ url_for('cadastros.relatorio_fundos_sem_cadastro') }}">Fundos sem Tipo</a>

<table class="table">
    
    <thead>
        <th>Fundo</th>
        <th>Codigo</th>
    
    </thead>    


    <tbody>
                
 

            {% for fundo in fundos %}
            <tr>

            <td>{{ fundo['codigo'] }}</td>
            
            <td>{{ fundo['razaoSocial'] }}</td>
             
            <td><a class='btn btn-primary' href={{ url_for('cadastros.editarFundo') }}?id={{fundo['id']}}>Detalhe</a></td>

        </tr>
    
            {% endfor %}
   

  




    </tbody>



</table>





{% endblock %}

InformesLegais/templates/main_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Informes Legais SQ{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('home')}}">
                                <span data-feather="home"></span>
                                Inicio
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('cadastros.list_fundos_template')}}">
                                <span data-feather="home"></span>
                                Cadastro de Fundos Jcot
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("cadastros.buscarFundosJcot") }}">
                                <span data-feather="file"></span>
                                Sincronizar Cadastros
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("cadastros.administradores") }}">
                                <span data-feather="shopping-cart"></span>
                                Administradores
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={{ url_for("geracao_informes.gerar_arquivo_5401") }}>
                                <span data-feather="bar-chart-2"></span>
                                Gerar Arquivo 5401
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={{ url_for("cadastros.jobs") }}>
                                <span data-feather="layers"></span>
                                Jobs em Andamento
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={{ url_for("controles.home_controles") }}>
                                <span data-feather="layers"></span>
                                Controles
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>



            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="mt-4">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div id="flash-messages primary">
                    {% for category, message in messages %}
                        <div class="alert-primary alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

InformesLegais/templates/new_home.html
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="static/output.css" rel="stylesheet">



</head>
<body>
<div class="bg-white">
  <header class="absolute inset-x-0 top-0 z-50">
    <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Product</a>
        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Features</a>
        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Marketplace</a>
        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Company</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Log in <span aria-hidden="true">&rarr;</span></a>
      </div>
    </nav>
    <!-- Mobile menu, show/hide based on menu open state. -->
    <div class="lg:hidden" role="dialog" aria-modal="true">
      <!-- Background backdrop, show/hide based on slide-over state. -->
      <div class="fixed inset-0 z-50"></div>
      <div class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
        <div class="flex items-center justify-between">
          <a href="#" class="-m-1.5 p-1.5">
            <span class="sr-only">Your Company</span>
            <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="">
          </a>
          <button type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Close menu</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="mt-6 flow-root">
          <div class="-my-6 divide-y divide-gray-500/10">
            <div class="space-y-2 py-6">
              <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Product</a>
              <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Features</a>
              <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Marketplace</a>
              <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Company</a>
            </div>
            <div class="py-6">
              <a href="#" class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Log in</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="relative isolate px-6 pt-14 lg:px-8">
    <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
      <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
      <div class="hidden sm:mb-8 sm:flex sm:justify-center">
        <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
          Announcing our next round of funding. <a href="#" class="font-semibold text-indigo-600"><span class="absolute inset-0" aria-hidden="true"></span>Read more <span aria-hidden="true">&rarr;</span></a>
        </div>
      </div>
      <div class="text-center">
        <h1 class="text-balance text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Data to enrich your online business</h1>
        <p class="mt-6 text-lg leading-8 text-gray-600">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.</p>
        <div class="mt-10 flex items-center justify-center gap-x-6">
          <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Get started</a>
          <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Learn more <span aria-hidden="true">→</span></a>
        </div>
      </div>
    </div>
    <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]" aria-hidden="true">
      <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
  </div>
</div>

</body>
</html>